import type { Metadata } from "next";
import { Geist, Lexend } from "next/font/google";
import "./globals.css";

import { Analytics } from "@vercel/analytics/react"

const geist = Geist({
  subsets: ['latin'],
  variable: '--font-geist',
});

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.variable} ${lexend.variable} antialiased`}>
      <body className={geist.className}>
      <Analytics />
        {children}
      </body>
    </html>
  );
}
